apiVersion: v2
name: odoo
description: Mint System Odoo
home: https://kubernetes.build
maintainers:
  - name: Mint System GmbH
    email: support@mint-system.ch
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: postgres
    version: 0.1.0
    repository: "file://../postgres"
    condition: postgres.enabled
  - name: vshnPostgres
    version: 0.1.0
    repository: "file://../vshnPostgres"
    condition: vshnPostgres.enabled
  - name: postgresql
    version: 16.7.21
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  # - name: cloudnative-pg
  #   version: 0.25.0
  #   repository: https://cloudnative-pg.github.io/charts
  #   condition: cnpg.enabled
