apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-hugo
  labels:
    app: hugo
spec:
  selector:
    matchLabels:
      app: hugo
  template:
    metadata:
      labels:
        app: hugo
    spec:
      containers:
        - name: odoo
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          - containerPort: 1313
