apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-odoo
  labels:
    app: odoo
spec:
  selector:
    matchLabels:
      app: odoo
  template:
    metadata:
      labels:
        app: odoo
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- range .Values.imagePullSecrets }}
        - name: {{ .name }}
        {{- end }}
      {{- end }}
      initContainers:
        - name: init
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          command:
            - /bin/bash
            - -c
            - |
              {{- if .Values.downloadOdooEnterprise }}/entrypoint.sh download-git-archive && \{{- end }}
              /entrypoint.sh git-clone-addons && \
              /entrypoint.sh init-db
          envFrom:
            - secretRef:
                name: {{ .Values.githubAddonsCredentialsSecretName }}
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            {{- if .Values.cnpg.enabled }}
            - name: PGHOST
              value: {{ .Release.Name }}-odoo-db-rw.{{ .Release.Namespace }}.svc.cluster.local
            - name: PGUSER
              value: {{ .Values.cnpg.cluster.bootstrap.initdb.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-odoo-db-app
                  key: password
            {{- end }}
          {{- if .Values.persistence.addons.enabled }}
          volumeMounts:
          - name: odoo-addons-storage
            mountPath: {{ .Values.persistence.addons.mountPath }}
          {{- end }}
      containers:
        - name: odoo
          image: {{ .Values.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          ports:
          - containerPort: 8069
          envFrom:
            - secretRef:
                name: {{ .Values.githubAddonsCredentialsSecretName }}
            - configMapRef:
                name: {{ .Release.Name }}-configmap
          env:
            {{- if .Values.cnpg.enabled }}
            - name: PGHOST
              value: {{ .Release.Name }}-odoo-db-rw.{{ .Release.Namespace }}.svc.cluster.local
            - name: PGUSER
              value: {{ .Values.cnpg.cluster.bootstrap.initdb.user }}
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-odoo-db-app
                  key: password
            {{- end }}
            {{- if .Values.externalServices.meilisearch.enabled }}
            - name: PUBLIC_MEILISEARCH_HOST
              value: "http://{{ tpl .Values.externalServices.meilisearch.serviceName . }}:{{ .Values.externalServices.meilisearch.port }}"
            {{- end }}
            {{- if .Values.extraEnv }}
            {{- .Values.extraEnv | nindent 12 }}
            {{- end }}
          {{- if or .Values.persistence.addons.enabled .Values.persistence.filestore.enabled }}
          volumeMounts:
          {{- if .Values.persistence.addons.enabled }}
          - name: odoo-addons-storage
            mountPath: {{ .Values.persistence.addons.mountPath }}
          {{- end }}
          {{- if .Values.persistence.filestore.enabled }}
          - name: odoo-filestore-storage
            mountPath: {{ .Values.persistence.filestore.mountPath }}
          {{- end }}
          {{- end }}
      {{- if or .Values.persistence.addons.enabled .Values.persistence.filestore.enabled }}
      volumes:
      {{- if .Values.persistence.addons.enabled }}
      - name: odoo-addons-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.addons.existingClaim | default (printf "%s-odoo-addons-pvc" .Release.Name) }}
      {{- end }}
      {{- if .Values.persistence.filestore.enabled }}
      - name: odoo-filestore-storage
        persistentVolumeClaim:
          claimName: {{ .Values.persistence.filestore.existingClaim | default (printf "%s-odoo-filestore-pvc" .Release.Name) }}
      {{- end }}
      {{- end }}


