apiVersion: v1
kind: Service
metadata:
  name: odoo
spec:
  selector:
    app: odoo
  ports:
    - port: 8069
      targetPort: 8069
---
apiVersion: v1
kind: Service
metadata:
  name: odoo-gevent
spec:
  selector:
    app: odoo
  ports:
    - port: 8072
      targetPort: 8072
