on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "main"

jobs:
  task-all:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      - name: Clone taskfile
        run: ./task clone-taskfile
      - name: Template .env
        run: ./task template-dotenv
      - name: Test chart odoo
        run: ./task test-chart-odoo
